### ISSUE TITLE
Suggest setting the exact package version for torch in requirements.txt

### ISSUE THREAD

**Issue by jmhb0** [royerlab/cytoself#30]
I ran the install instructions on the README and tried running `example_scripts/simple_example.py`, but I got some error todo with the `torch.nn.Upsample` layer (sorry I forgot to save the error). 

I was able to fix it by downgrading torch from >2.0 to 1.13.1. So maybe some issue was introduced when torch 2.0 launched. 

I don't know if this is affecting others, but you might be able to avoid the issue by setting the exact torch version that you used in the `requirements.txt`.

**Comment by li-li-github** [comment]
Hi @jmhb0 thank you again for the bug report!
Yes, I also caught the error. The issue was that the `size` argument in `Upsample` must be `int` whereas I was passing `numpy.int`. The issue should be fixed in the PR. I tested it on pytorch 2.1.0. Let me know if it works for you too. Just FYI, bilinear upsampling may not be implemented in pytorch if you try to use 16bit precision or macOS MPS.

**Comment by jmhb0** [comment]
Thanks! That is a better fix :)
