### ISSUE TITLE
How to normalize the nuclear distance channel?

### ISSUE THREAD

**Issue by JimmyCai91** [royerlab/cytoself#7]
Hi, great work!

Image data downloaded from those image_data0x.npy files has un-normalized nuclear distance channel. Would be nice if you can provide the way that to normalize the channel to -1 and 1. 

Thanks.

**Comment by li-li-github** [comment]
Hi,

We didn't normalize nuclear distance and I think you shouldn't. Instead, it is rescaled by 0.01.
https://github.com/royerlab/cytoself/blob/0133ab6c45d990cbfb1ab25361facd2c43940a04/cytoself/datamanager/opencell.py#L69

**Comment by Yuangaga** [comment]
Hi @li-li-github. 

Thanks for your advice. As suggested, I have successfully achieved nuclear segmentation with StarDist. 
<img width="1327" alt="截屏2022-11-15 下午2 57 56" src="https://user-images.githubusercontent.com/42559961/201850923-6abdf7ce-e3c6-44fc-895a-7da3c5df19b9.png">

But, I'm also curious about how to get the nucleus distance matrix from the segmented picture. Could I reference the code for computing nucleus distance? Thanks.

<img width="1165" alt="截屏2022-11-15 下午2 53 59" src="https://user-images.githubusercontent.com/42559961/201850723-3a76e273-2f88-47e8-8823-7bb0a3509e0d.png">

**Comment by li-li-github** [comment]
Hi @JimmyCai91 and @Yuangaga 
I'm very sorry for the late reply. 
After checking my old code and recalling my memory, I think what I meant was
making `-1 <= the values in the nuclear distance channel =< 1`
So it's not "normalized."

This was done by rescaling the channel with 0.01. Throughout the whole dataset that we are offering in this repo, the min value of the nuclear distance channel after rescaling is -1.053 and there are only 118 pixels that are lower than -1, so they should be negligible. 
The max value is well below 1.

The idea of making the nuclear distance in [-1, 1] was because, without rescaling, the large values in the nuclear distance channel would overwhelm other channels, resulting in unsuccessful training.

I hope this answered your question.

**Comment by JimmyCai91** [comment]
> 

Hi @li-li-github ,

Thanks for the reply. It reads great! 
I will close this issue. 

Thanks, 

--- 

@Yuangaga if you need, feel free to reopen this issue.
